spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MYSQL8Dialect
          format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
api:
  prefix: /api/v1
jwt:
  expiration: 1296000           # 1 giờ - dễ test
  expiration-refresh-token: 2592000  # 30 ngày
  secretKey: BNXbZLuOZATSXFzP+DyGlqmM9CXaRI3d3JTTE5bOd0E=

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.filter: DEBUG

#swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

#health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: "health, info"

vnpay:
  # URL để redirect người dùng sang trang thanh toán sandbox của VNPAY
  # (môi trường test, dùng để nhập thông tin thẻ, ngân hàng)
  vnp-url:  https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

  # URL mà VNPAY sẽ redirect về sau khi thanh toán xong (hoặc huỷ)
  # → Đây là endpoint trên server của bạn để xử lý kết quả trả về
  vnp-return-url:  https://c3391336eaf6.ngrok-free.app/api/v1/payments/vnpay-return

  # Mã website (Terminal code) được VNPAY cấp cho bạn khi đăng ký
  # → dùng để định danh merchant của bạn trong hệ thống VNPAY
  vnp-tmn-code: E4Q79PC9

  # Chuỗi bí mật (secret key) VNPAY cấp để ký (hash) dữ liệu
  # → dùng để kiểm tra tính toàn vẹn của dữ liệu request/response
  vnp-hash-secret: PH83A7NASMB41PF3HG6UXUFV1OUIFQCY

  # API của VNPAY để gọi các tác vụ phía server (truy vấn giao dịch, hoàn tiền…)
  # Đây là endpoint dùng trong môi trường sandbox
  vnp-api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
momo:
  partner-code: MOMO
  access-key: F8BBA842ECF85
  secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
  endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  return-url:  https://c3391336eaf6.ngrok-free.app/api/v1/payments/momo-return
  notify-url:  https://c3391336eaf6.ngrok-free.app/api/v1/payments/momo-notify
zalopay:
  app-id: 2553
  key1: PcY4iZIKFCIdgZvA6ueMcMHHUbRLYjPL
  key2: kLtgPl8HHhfvMuDHPwKfgfsY4Ydm9eIz
  endpoint: https://sb-openapi.zalopay.vn/v2
  callback-url:  https://c3391336eaf6.ngrok-free.app/api/v1/payments/zalopay/callback
  redirect-url:  https://c3391336eaf6.ngrok-free.app/api/v1/payment-result
